name: test-github-action
on:
  push:
  schedule:
    - cron: '30 * * * *'

jobs:
  run_python_program:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7.16'
      - name: Install python packages
        run: pip install requests
      - name: Run app
        run: python -m oteme.app
      - name: Commit changes
        run: git add . && git commit -m "Edit collect file" && git push origin
