name: collect-weather-data
on: push

jobs:
  run_python_program:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7.16'
      - name: Install python packages
        run: pip install requests
      - name: List and show directories
        run: ls

